### ISSUE TITLE
Second Patreon Characters Crusade

### ISSUE THREAD

**Issue by hamjustine** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#1353]
ℹ️ **Development Notice**: Please note that this branch is based on [1-8-1-update](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2/tree/1-8-1-update), which means it **_should not_** be merged into `master` until after the `1-8-1-update` branch has been merged.

### Links:
- 📗 [Life-Binder Codex of Eonar](https://docs.google.com/spreadsheets/d/1hKQmfMrI_d8FtRez5w68OfS1s0JVr5r2yF8nryGe104)

## Changelog:
- Added **~XX** Patreon characters.

### Draenei

**Courtiers**
**Counts**
**Barons**

### Dwarves

**Counts**

**Barons**

**Courtiers**

### Gnolls

**Courtiers**

### Goblins

**Counts**

### Highborne

**Courtiers**

### High Elves

**Counts**

**Courtiers**

### Humans

**Counts**

**Courtiers**

### Liches

**Counts**

**Courtiers**

### Murlocs

**Courtiers**

### Night Elves

**Counts**

**Courtiers**

### Orcs

**Courtiers**

### Tauren

**Courtiers**

### Vrykul

**Counts**

## To-do list:
- [ ] Give lands to characters.
- [ ] Balance the traits of characters. Customization points must not exceed achievement limit.
- [x] Check other characters for balance issues and note this in [the spreadsheet](https://docs.google.com/spreadsheets/d/1hKQmfMrI_d8FtRez5w68OfS1s0JVr5r2yF8nryGe104).
