### ISSUE TITLE
Adding New Broken Isles Races, Religions and Culture for mapping

### ISSUE THREAD

**Issue by ElMariuso** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#148]
To prepare the mapping, I think that we should already add the races, religions and cultures of the Broken Isles.

**Vrykuls:**
 - [x] _Culture_: Stormir (To give a different culture to the Vrykul here than to those in Northrend. They are separated, so it is normal that they have different cultures.) Added
 
**Nightborne:**
- [x] _Religion:_ Shalarism (Cult of Nightwell) #222/#309 Merged
- [x] _Culture:_ Shalassian (from their language) Added
- [x] _Race trait:_ Nightborne/Shal'dorei #222/#291 #291 Merged

**Highmountain Taurens**
- [x] _Culture:_ Highmountain (tauren group) Added
- [x] _Race trait_: Does they need specific race trait with blessing of Eche'ro ?  #306 Merged

**Drogbar**
- [ ] _Religion:_ I don't know their religion but they seem to revere things related to Deathwing. So probably we can create a dragon religion to worship Deathwing, which would also be the religion of the black dragons. #344
- [x] _Culture:_ Drogbar (Trogg group) #295 Merged
- [x] _Race trait:_ Drogbar  #295 Merged

**Comment by zumbak04** [comment]
> * _Religion:_ I don't know their religion but they seem to revere things related to Deathwing. So probably we can create a dragon religion to worship Deathwing, which would also be the religion of the black dragons.

They should have the same religion as Deathwind and Deathwind is a N'zoth follower.

**Comment by Delnarzok** [comment]
Chiming in to say that while the Drogbar were slaves to Deathwing, they were freed by Huln Highmountain after the war of the ancients (You can see visions of this in game where Huln banish Deathwing to Deepholm). Since then, they're mostly been a peaceful shamanistic people.

Aside from rocks, they have been worshipping giant worms like Naraxas, the boss in the Neltarion Lair dungeon.

There are some Drogbar that joined the twilight hammer cult and worship the void though like the Necrodark tribe.

**Comment by zumbak04** [comment]
> Chiming in to say that while the Drogbar were slaves to Deathwing, they were freed by Huln Highmountain after the war of the ancients (You can see visions of this in game where Huln banish Deathwing to Deepholm). Since then, they're mostly been a peaceful shamanistic people.
> 
> Aside from rocks, they have been worshipping giant worms like Naraxas, the boss in the Neltarion Lair dungeon.
> 
> There are some Drogbar that joined the twilight hammer cult and worship the void though like the Necrodark tribe.

I see. Don't know much of their lore, need to research it before doing them.

**Comment by ElMariuso** [comment]
> 
> 
> > > * _Religion:_ I don't know their religion but they seem to revere things related to Deathwing. So probably we can create a dragon religion to worship Deathwing, which would also be the religion of the black dragons.
> > 
> > 
> > They should have the same religion as Deathwind and Deathwind is a N'zoth follower.
> 
> Chiming in to say that while the Drogbar were slaves to Deathwing, they were freed by Huln Highmountain after the war of the ancients (You can see visions of this in game where Huln banish Deathwing to Deepholm). Since then, they're mostly been a peaceful shamanistic people.
> 
> Aside from rocks (Earthmother religion?), they have been worshipping giant worms like Naraxas, the boss in the Neltarion Lair dungeon.
> 
> There are some Drogbar that joined the twilight hammer cult and worship the void though like the Necrodark tribe.

"Troggs worship the massive reptiles known as salamanders. Troggs will attempt to capture and train young salamanders as mounts. If these primitive humanoids slay or encounter a slain salamander, they will feast on its remains and make crude armor and weapons from its claws, teeth, and hide."

Troggs also worship animals as a result, such as Drogbars. Either we give them a fetichistic religion or we create a new religion.
