### ISSUE TITLE
Arthas' Event Chain

### ISSUE THREAD

**Issue by zumbak04** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth-2#777]
**Describe your suggestion in full detail below:**
Inspired by the Rise of the Lich King book.

[WC3 Human Campaign](https://wowpedia.fandom.com/wiki/Scourge_of_Lordaeron) for reference.

Quoting the WC3 or the Rise of the Lich King book is very welcome.

Need to say there may be no Arthas, Terenas, Uther, but the game will pick a replacement for them.

All texts should be in the **_Present Form_**.

24 texts in sum, wow!

# Part 1

- **Start**
- [x] **Event:** Terenas II (or any Lordaeron king) hears rumors about the Plague
  - **Option 1:** send your son (or a trusted knight) to find out
  - **Option R:** don't send anyone, Arthas may ignore you anyway
  - [x] Write text, 600-500 characters, in 1st person, from Terenas' perspective
- [x] **Event:** Arthas gather a group to investigate the Plague. Can tell about the Plague here.
  - **Option 1:** join a group, for an invited group member
  - **Option 2:** don't join, for an invited group member
  - **Option R:** just a reaction
  - [x] Write text, 600-500 characters, in 1st person, from Arthas' or invited group member perspective
- [x] **Activity:** everyone participating is assigned to the same activity
  - From this point, we may influence them: add wounds, kill, etc.
- [x] **Event:** everything around looks dead, you find an abandoned farm, is attacked by undead inside, briefly see Kel'Thuzad
  - **Option R:** just a reaction
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (including Arthas)
- [x] **Event:** you meet Kel'Thuzad in Andorhal (or another plague center), Kel'Thuzad tells about Mal'Ganis
  - **Option 1:** Arthas send troops to kill Kel'Thuzad
  - **Option R:** just a reaction for group perspective (excluding Arthas)
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (including Arthas)
- [x] **Event:** you chase Mal'Ganis, rest in Heartglen (or any other city), find out the Plague turns undead, instead of killing, is attacked by a huge undead army
  - **Option 1:** Arthas fights
  - **Option R:** just a reaction for group perspective (excluding Arthas)
  - [x] Write text, 600-500 characters, in 1st person, from any group member perspective
- [x] **Event:** you reach Stratholme (or any other big city), find out you're too late
  - **Option 1:** purge this entire city, you suffer small losses, huge prestige loss, development drops a lot, a small chance of curing the city, some group members like Jaina and Uther may abandon you
  - **Option 2:** evacuate, high chance of spreading the Plague, you suffer high losses
  - **Option 3:** put masks on, quarantine, prestige loss, development drops, you suffer medium losses
  - **Option R:** just a reaction for group perspective (excluding Arthas)
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (including Arthas)
- [x] **Event:** Arthas tells you about his decision (it depends on Arthas' decision above)
  - **Option 1:** Stay with Arthas
  - **Option 2:** Leave
  - [x] Write text for purging, 600-500 characters, in 1st person, from group perspective (excluding Arthas)
  - [x] Write text for evacuation, 600-500 characters, in 1st person, from group perspective (excluding Arthas)
  - [x] Write text for quarantine, 600-500 characters, in 1st person, from group perspective (excluding Arthas)
- [x] **Notification Event:** Arthas does what he wanted with the city (it depends on Arthas' decision above), Mal'ganis goes to Northrend
  - **Option 1:** chase Mal'ganis
  - **Option 2:** stay in Lordaeron
  - **Option R:** just a reaction
  - [x] Write text for purging, 600-500 characters, in 1st person, from the world perspective and group perspective (including Arthas) (can try to unite them or write 2 different openings)
  - [x] Write text for evacuation, 600-500 characters, in 1st person, from the world perspective and group perspective (including Arthas) (can try to unite them or write 2 different openings)
  - [x] Write text for quarantine, 600-500 characters, in 1st person, from the world perspective and group perspective (including Arthas) (can try to unite them or write 2 different openings)
- [x] **Event:** Arthas tells you about his plan to sail Northrend to chase Mal'ganis
  - **Option 1:** follow him
  - **Option 2:** I'm out
  - [x] Write text, 600-400 characters, in 1st person, from group perspective (excluding Arthas)

# Part 2

- **_If you select evacuation or purging, you may keep chasing Mal'Ganis to Northrend_**
- [x] **Event:** Terenas find out Arthas sailed Northrend with an army
  - **Option 1:** Bring him back
  - **Option 2:** THAT'S MY BOI
  - [x] Write text, 600-500 characters, in 1st person, from Terenas perspective
- [x] **Event:** you arrive in Northrend, Muradin joins, telling about the Frostmourne
  - **Option R:** just a reaction
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (excluding Arthas)
  - [x] Write text, 600-500 characters, in 1st person, from Arthas perspective, should mention not feeling cold and seeing dreams about the blade
- [x] **Event:** Terenas calls you back home
  - **Option Burn:** burn the ships so they can't run, for Arthas
  - **Option Let Run:** let them run but you stay, for Arthas
  - **Option Run:** you leave with the ships, for group (excluding Arthas)
  - **Option Stay:** you stay, for group (excluding Arthas)
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (including Arthas)
- [x] **Event:** Arthas burns the ships with help of mercenaries
  - **Option 1:** Kill the mercenaries
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (excluding Arthas)
  - [x] Write text, 600-500 characters, in 1st person, from Arthas perspective
- [x] **Event:** we find Frostmourne, Muradin reads the warning, Arthas takes the sword, Muradin is wounded
  - **Option 1:** I will give anything or pay any price, if only you will help me save my people.
  - **Option 2:** Argh! for Muradin
  - [x] Write text, 600-500 characters, in 1st person, from Arthas perspective
- [x] **Event:** Arthas cuts undead hordes, kills Mal'Ganis, disappears in snowfall
  - **Option R:** just a reaction
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (excluding Arthas)
  - [x] Write text, 600-500 characters, in 1st person, from Arthas perspective
- [x] **Event:** Arthas comes for you and resurrects as undead
  - **Option R:** just a reaction
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (excluding Arthas)
- [x] **Event:** you return home, they welcome you like heroes, you enter the throne room
  - **Option A:** You no longer need to bear the weight of your crown. I've taken care of everything.
  - **Option T:** What are you doing, my son?
  - **Option R:** stay behind Arthas
  - [x] Write text, 600-500 characters, in 1st person, from Arthas perspective (including Arthas, they all are undead at this point)
  - [x] Write text, 600-500 characters, in 1st person, from group perspective (excluding Arthas, they all are undead at this point)
  - [x] Write text, 600-500 characters, in 1st person, from Terenas perspective
- [x] **Notification Event:** massacre in Lordaeron, body piles with nobles, commoners lay on streets, everyone is equal before Death
  - **Option R:** just a reaction
  - [x] Write text, 600-500 characters, in 1st person, from the world perspective and group perspective (including Arthas) (can try to unite them or write 2 different openings)
- **End**

# Fallback
- [x] **Event:** Arthas dies so you return back home
  - **Option R:** just a reaction
  - [x] Write text, 600-400 characters, in 1st person, from a group member perspective

# Medivh Line
**_LATER_**
